baseURL = "/"
languageCode = "zh-cn"
title = "我的博客"
theme = "blowfish"
defaultContentLanguage = "zh-cn"

# 主题配置
[params]
  # 网站描述
  description = "分享技术，记录生活"
  
  # 配置主题外观
  colorScheme = "blowfish"
  defaultAppearance = "light"
  autoSwitchAppearance = true
  enableSearch = true
  
  # 主页配置
  [params.homepage]
    layout = "profile"
    showRecent = true
    cardView = true

  # 文章配置
  [params.article]
    showDate = true
    showDateUpdated = true
    showAuthor = true
    showBreadcrumbs = true
    showDraftLabel = true
    showEdit = false
    editURL = ""
    editAppendPath = true
    showHeadingAnchors = true
    showPagination = true
    invertPagination = false
    showReadingTime = true
    showTableOfContents = true
    showTaxonomies = true
    showWordCount = true
    showSummary = true
    sharingLinks = ["twitter", "github", "email"]

  # 作者信息
  [params.author]
    name = "博主"
    headline = "热爱技术，热爱生活"
    bio = "一个对技术充满热情的程序员"
    image = "img/author.jpg"  # 可以添加你的头像

  # 社交媒体链接
  [[params.socialLinks]]
    icon = "github"
    title = "GitHub"
    url = "https://github.com/yourusername"

  [[params.socialLinks]]
    icon = "twitter"
    title = "Twitter"
    url = "https://twitter.com/yourusername"

  # 页脚配置
  [params.footer]
    showCopyright = true
    showThemeAttribution = true
    showAppearanceSwitcher = true
    showScrollToTop = true

# 菜单配置
[[menu.main]]
  name = "首页"
  pageRef = "/"
  weight = 10

[[menu.main]]
  name = "文章"
  pageRef = "posts"
  weight = 20

[[menu.main]]
  name = "关于"
  pageRef = "about"
  weight = 30

[markup]
  [markup.highlight]
    noClasses = false
    lineNos = true
    style = "monokai"

[taxonomies]
  tag = "tags"
  category = "categories"
  
[security]
  [security.funcs]
    getenv = ['^HUGO_']
